name: Project Signals (typescript check, linting & prettier)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check-signals:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install project dependencies
        run: npm ci

      - name: Check for typescript errors
        run: npm run ts-check

      - name: Check for lint errors
        run: npm run lint

      - name: Check for prettier errors
        run: npm run prettier-check
